### ISSUE TITLE
Falsches View geht auf

### ISSUE THREAD

**Issue by Yanis-Weibel** [RookStudios/Lernkartei#34]
wenn mann das Helpview einmal geöffnet hat es schließt und dann bei denn Optionen zurück will geht nur noch das Helpview auf.

@miro-albrecht @Nina-Egger

**Comment by miro-albrecht** [comment]
@hlucca

**Comment by hlucca** [comment]
Neue Navigation. Alle views rufen jetzt getFXController() statt getController auf,
