### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Joel-Haeberli** [RookStudios/Lernkartei#48]
Die Datenbank muss so schnell wie möglich überarbeitet oder sogar neu erstellt werden! Hat erste Priorität. Wäre gut wenn wir das Morgen anschauen könnten.

Die Klassen, welche man beim abspeichern benötigt, bestehen nach dem neu erstellten ERM und Klassendiagramm bereits. Man muss jetzt noch die Datenbank selber anlegen.

Habe heute noch eine Idee gehabt. Werde ich morgen vortragen.

@rogerschneiter und @hlucca

**Comment by hlucca** [comment]
Datenbank jetzt neu und flexibel, Dokumnierung folgt noch
